server:
  port: 8900

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: MySQL
        database_platform: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: jdbc:mariadb://localhost:3306/lc8
    username: root
    password:
#    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver

